Traceback (most recent call last):
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/project/PromotionsQrBot/middlewares/MiddleWares.py", line 103, in __call__
    await event.answer(
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/client/bot.py", line 453, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py", line 185, in make_request
    response = self.check_response(
  File "/home/project/PromotionsQrBot/venv/lib/python3.10/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "3" at byte offset 28
